// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RadamantAPI.Models
{
    [Table("CheckPointStaff")]
    public partial class CheckPointStaff
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("CheckPointID")]
        public int CheckPointId { get; set; }
        [Column("StaffID")]
        public int StaffId { get; set; }

        [ForeignKey("CheckPointId")]
        [InverseProperty("CheckPointStaffs")]
        public virtual CheckPoint CheckPoint { get; set; }
        [ForeignKey("StaffId")]
        [InverseProperty("CheckPointStaffs")]
        public virtual Staff Staff { get; set; }
    }
}