// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RadamantAPI.Models
{
    public partial class Person
    {
        public Person()
        {
            WicketLogs = new HashSet<WicketLog>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(50)]
        public string FirstName { get; set; }
        [Required]
        [StringLength(50)]
        public string LastName { get; set; }
        public bool Status { get; set; }
        [Required]
        [Column("KeyGUID")]
        [StringLength(36)]
        public string KeyGuid { get; set; }
        [Required]
        [StringLength(10)]
        public string Passport { get; set; }

        [InverseProperty("Person")]
        public virtual ICollection<WicketLog> WicketLogs { get; set; }
    }
}