// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RadamantAPI.Models
{
    public partial class SecurityMessage
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("CheckPointID")]
        public int CheckPointId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }

        [ForeignKey("CheckPointId")]
        [InverseProperty("SecurityMessages")]
        public virtual CheckPoint CheckPoint { get; set; }
    }
}