// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RadamantAPI.Models
{
    [Index("Login", Name = "IX_Staff", IsUnique = true)]
    public partial class Staff
    {
        public Staff()
        {
            CheckPointStaffs = new HashSet<CheckPointStaff>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(20)]
        public string Login { get; set; }
        [Required]
        [StringLength(10)]
        public string PassHash { get; set; }
        public bool Status { get; set; }

        [InverseProperty("Staff")]
        public virtual ICollection<CheckPointStaff> CheckPointStaffs { get; set; }
    }
}