// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RadamantAPI.Models
{
    public partial class WicketLog
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("WicketID")]
        public int WicketId { get; set; }
        [Column("PersonID")]
        public int PersonId { get; set; }
        [Column("StatusID")]
        public int? StatusId { get; set; }
        [StringLength(250)]
        public string Message { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }

        [ForeignKey("PersonId")]
        [InverseProperty("WicketLogs")]
        public virtual Person Person { get; set; }
        [ForeignKey("StatusId")]
        [InverseProperty("WicketLogs")]
        public virtual LogStatus Status { get; set; }
        [ForeignKey("WicketId")]
        [InverseProperty("WicketLogs")]
        public virtual Wicket Wicket { get; set; }
    }
}