// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace RadamantAPI.Models
{
    public partial class Wicket
    {
        public Wicket()
        {
            WicketLogs = new HashSet<WicketLog>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        public bool Status { get; set; }
        [Column("CheckPointID")]
        public int CheckPointId { get; set; }

        [ForeignKey("CheckPointId")]
        [InverseProperty("Wickets")]
        public virtual CheckPoint CheckPoint { get; set; }
        [InverseProperty("Wicket")]
        public virtual ICollection<WicketLog> WicketLogs { get; set; }
    }
}